[package]
name = "sistema-solar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35"
tobj = "3.2"
glam = "0.24"
rand = "0.8"
